name: "DavidX's Blog"
description: "Programming and more personal thoughts."

avatar: https://davidx.us.kg/images/avatar.png
favicon: https://davidx.us.kg/images/favicon.ico

navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Tags
    url: /tags
  - name: Feedback
    url: /feedback

paginate: 8

gitalk:
  clientID: Ov23liFjaB3m2aO8lSRN
  clientSecret: 2f599b4040c753c344afd394517635fa5cca5473
  repo: blog-comments-davidx
  owner: Davidasx

excerpt_separator: <!-- more -->

footer-links:
  email: davidx@davidx.us.kg
  github: Davidasx
  rss:  this_is_rss # nothing to change here

footer-text: Copyright (c) DavidX 2024 # your name here

url: davidx.us.kg

# do not change anything below this line!

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments synt
  math_engine: MathJax

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

